# permissions to do viewer nginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-viewer-role
rules:
- apiGroups:
  - ingress.ingress-nginx.io
  resources:
  - nginxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress.ingress-nginx.io
  resources:
  - nginxes/status
  verbs:
  - get
